// <auto-generated />
using System;
using CourseApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseApi.Migrations
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20260515103348_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseApi.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "An introduction to artificial intelligence and machine learning.",
                            Duration = "13 hr 35 min",
                            ImageUrl = "/images/ai.png",
                            LessonCount = 15,
                            Title = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Description = "Learn how to analyse and work with large sets of data.",
                            Duration = "20 hr 40 min",
                            ImageUrl = "/images/data-science.png",
                            LessonCount = 25,
                            Title = "Data Science & Analytics"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Description = "Understand the basics of marketing in a digital world.",
                            Duration = "1 hr 18 min",
                            ImageUrl = "/images/digital-marketing.png",
                            LessonCount = 5,
                            Title = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Description = "Learn how to design user friendly interfaces from scratch.",
                            Duration = "27 hr 55 min",
                            ImageUrl = "/images/uiux.png",
                            LessonCount = 34,
                            Title = "UI/UX Design for Beginner"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Description = "Build complete web applications with both frontend and backend.",
                            Duration = "24 hr 45 min",
                            ImageUrl = "/images/fullstack.png",
                            LessonCount = 30,
                            Title = "Full stack Developer"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Description = "Get started with Sketch and learn the basics of digital design.",
                            Duration = "14 hr 25 min",
                            ImageUrl = "/images/sketch.png",
                            LessonCount = 18,
                            Title = "Sketch for Designer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
